# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eat-it' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm'
  pod 'RealmSwift', '3.3.0'
  pod 'SnapKit', '~> 4.0'
  # Pods for Eat-it


end
