# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Eat-it' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Realm'
  pod 'RealmSwift'
  pod 'SnapKit', '~> 4.2.0'
  pod 'Fabric'
  #pod 'Crashlytics'
  pod 'Answers'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  # Pods for Eat-it
end

target 'Eat-itTodayExtension' do
  use_frameworks!
  pod 'Realm'
  pod 'RealmSwift'
end
